<?xml version="1.0" encoding="utf-8"?><testsuite errors="2" failures="0" name="pytest" skips="0" tests="2" time="0.332"><testcase classname="" file="mne/realtime/tests/test_lsl_client.py" name="mne.realtime.tests.test_lsl_client" time="0"><error message="collection failure">&lt;frozen importlib._bootstrap&gt;:888: in _find_spec
    ???
E   AttributeError: &apos;AssertionRewritingHook&apos; object has no attribute &apos;find_spec&apos;

During handling of the above exception, another exception occurred:
../../../../anaconda3/lib/python3.6/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
&lt;frozen importlib._bootstrap&gt;:971: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:951: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:890: in _find_spec
    ???
&lt;frozen importlib._bootstrap&gt;:864: in _find_spec_legacy
    ???
../../../../anaconda3/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:164: in find_module
    source_stat, co = _rewrite_test(self.config, fn_pypath)
../../../../anaconda3/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:412: in _rewrite_test
    rewrite_asserts(tree, fn, config)
../../../../anaconda3/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:461: in rewrite_asserts
    AssertionRewriter(module_path, config).run(mod)
../../../../anaconda3/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:702: in run
    new.extend(self.visit(child))
../../../../anaconda3/lib/python3.6/ast.py:253: in visit
    return visitor(node)
../../../../anaconda3/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:818: in visit_Assert
    lineno=assert_.lineno,
E   _pytest.warning_types.PytestWarning: assertion is always true, perhaps remove parentheses?</error><error message="collection failure">&lt;frozen importlib._bootstrap&gt;:888: in _find_spec
    ???
E   AttributeError: &apos;AssertionRewritingHook&apos; object has no attribute &apos;find_spec&apos;

During handling of the above exception, another exception occurred:
../../../../anaconda3/lib/python3.6/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
&lt;frozen importlib._bootstrap&gt;:971: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:951: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:890: in _find_spec
    ???
&lt;frozen importlib._bootstrap&gt;:864: in _find_spec_legacy
    ???
../../../../anaconda3/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:164: in find_module
    source_stat, co = _rewrite_test(self.config, fn_pypath)
../../../../anaconda3/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:412: in _rewrite_test
    rewrite_asserts(tree, fn, config)
../../../../anaconda3/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:461: in rewrite_asserts
    AssertionRewriter(module_path, config).run(mod)
../../../../anaconda3/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:702: in run
    new.extend(self.visit(child))
../../../../anaconda3/lib/python3.6/ast.py:253: in visit
    return visitor(node)
../../../../anaconda3/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:818: in visit_Assert
    lineno=assert_.lineno,
E   _pytest.warning_types.PytestWarning: assertion is always true, perhaps remove parentheses?</error></testcase></testsuite>